<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ISCC.Api.Gate</RootNamespace>
    <AssemblyName>ISCC.Api.Gate</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ISCC.Shared.Contracts\ISCC.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\ISCC.Application\ISCC.Application.csproj" />
    <ProjectReference Include="..\..\ISCC.Infrastructure\ISCC.Infrastructure.csproj" />
    <ProjectReference Include="..\..\ISCC.Shared.Localization\ISCC.Shared.Localization.csproj" />
    <ProjectReference Include="..\..\ISCC.Shared.Web\ISCC.Shared.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

</Project>
