<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ISCC.Shared.Localization</RootNamespace>
    <AssemblyName>ISCC.Shared.Localization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Resource.Ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Ar.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
