<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ISCC.Web.Client</RootNamespace>
    <AssemblyName>ISCC.Web.Client</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ISCC.Application\ISCC.Application.csproj" />
    <ProjectReference Include="..\ISCC.Infrastructure\ISCC.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

</Project>
